###Create New User
POST http://localhost:4020/user/register/
Content-Type: application/json

{
    "name": "adsfadsf",
    "email": "adsfadsfasd@gmail.com",
    "password": "adsfadsgadsfasdf"
}
 
### Get Refresh Token
GET http://localhost:4020/user/refresh_token

### Login 
POST http://localhost:4020/user/login
Content-Type: application/json

{
    "email": "wittymohit@gmail.com",
    "password": "password"
}

### Logout
GET http://localhost:4020/user/logout

### getUser
GET http://localhost:4020/user/infor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOGMxNTE0NGU1ZTY0Mjc3NGFkMTM3YiIsImlhdCI6MTYxOTg2MTU0MSwiZXhwIjoxNjE5OTQ3OTQxfQ.YramlRqmjYxPLywv3s7-xF3MvzLxkf0p6P5gPxVd2GM